/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.49
 * Generated at: 2021-05-20 04:12:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1574778516596L));
    _jspx_dependants.put("jar:file:/F:/Data_structureSys/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/dataStructure/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098682290000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>数据结构算法可视化系统</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/global.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header class=\"app-header\">\r\n");
      out.write("    <div class=\"header-container\">\r\n");
      out.write("        <div class=\"searchBox\">\r\n");
      out.write("            <form id=\"searchForm\" action=\"queryAlgoByNameAcManageAlgorithmAction\" method=\"post\">\r\n");
      out.write("                <input type=\"text\" placeholder=\"请搜索想学习的算法\" name=\"searchName\" id=\"searchIpt\">\r\n");
      out.write("                <button type=\"submit\"></button>\r\n");
      out.write("            </form>\r\n");
      out.write("            <div id=\"search-drops\">\r\n");
      out.write("           \t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            </div> \r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"User-box\">\r\n");
      out.write("            <div class=\"User-dropdown\">\r\n");
      out.write("                <a class=\"dropdown\" id=\"User-dropdown-id\" href=\"mine.jsp\">\r\n");
      out.write("                    <span style=\"font: 16px 'Microsoft YaHei UI';color: #5d6778\">我的</span>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</header>\r\n");
      out.write("<!--<div class=\"footer\"></div>-->\r\n");
      out.write("<div class=\"leftPanel\">\r\n");
      out.write("    <div class=\"leftPanel-inner\">\r\n");
      out.write("        <div class=\"blank-div\"></div>\r\n");
      out.write("            <div class=\"left-nav\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                <li class=\"main-menu-li\"><span>查找</span>\r\n");
      out.write("                        <ul class=\"child-menu-ul\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"../animation/search/halfSearch/halfSearch.html\" target=\"iframe1\">\r\n");
      out.write("                                    <span>折半查找</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"notmade.html\" target=\"iframe1\">\r\n");
      out.write("                                    <span>B-树查找</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"../animation/search/hashSearch/hashSearch.html\" target=\"iframe1\">\r\n");
      out.write("                                    <span>散列表查找</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("                    <li class=\"main-menu-li\"><span>排序</span>\r\n");
      out.write("                        <ul class=\"child-menu-ul\">\r\n");
      out.write("                       \t \t<li>\r\n");
      out.write("                                <a href=\"../animation/sort/insertSort/insertSort.html\" target=\"iframe1\">\r\n");
      out.write("                                    <span>插入排序</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"../animation/sort/shellSort/shellSort.html\" target=\"iframe1\">\r\n");
      out.write("                                    <span>希尔排序</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"../animation/sort/bubbleSort/bubbleSort.html\" target=\"iframe1\">\r\n");
      out.write("                                    <span>冒泡排序</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"../animation/sort/quickSort/quickSort.html\" target=\"iframe1\">\r\n");
      out.write("                                    <span>快速排序</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"../animation/sort/selectSort/selectSort.html\" target=\"iframe1\">\r\n");
      out.write("                                    <span>选择排序</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                          <!--  <li>\r\n");
      out.write("                                <a href=\"notmade.html\" target=\"iframe1\">\r\n");
      out.write("                                    <span>堆排序</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"notmade.html\" target=\"iframe1\">\r\n");
      out.write("                                    <span>归并排序</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>  -->\r\n");
      out.write("                            \r\n");
      out.write("                        </ul>\r\n");
      out.write("\r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("                    <li class=\"main-menu-li\"><span>图</span>\r\n");
      out.write("                    \t<ul class=\"child-menu-ul\">\r\n");
      out.write("                    \t\t<li>\r\n");
      out.write("                                <a href=\"notmade.html\" target=\"iframe1\">\r\n");
      out.write("                                    <span>深度优先遍历</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                         \t</li>\r\n");
      out.write("                         \t<li>\r\n");
      out.write("                                <a href=\"notmade.html\" target=\"iframe1\">\r\n");
      out.write("                                    <span>广度优先遍历</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                          \t</li>\r\n");
      out.write("                          \t<li>\r\n");
      out.write("                                <a href=\"notmade.html\" target=\"iframe1\">\r\n");
      out.write("                                    <span>Prim算法求最小生成树</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                          \t</li>\r\n");
      out.write("                          \t<li>\r\n");
      out.write("                                <a href=\"notmade.html\" target=\"iframe1\">\r\n");
      out.write("                                    <span>kruskal算法求最小生成树</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                          \t</li>\r\n");
      out.write("                          \t<li>\r\n");
      out.write("                                <a href=\"notmade.html\" target=\"iframe1\">\r\n");
      out.write("                                    <span>Dijkstra求最短路径</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                          \t</li>\r\n");
      out.write("                          \t<li>\r\n");
      out.write("                                <a href=\"notmade.html\"  target=\"iframe1\">\r\n");
      out.write("                                    <span>Floyd求最短路径</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                          \t</li>\r\n");
      out.write("                         </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("                    <li class=\"main-menu-li\"><span>树</span>\r\n");
      out.write("                   \t <ul class=\"child-menu-ul\">\r\n");
      out.write("                    \t<li>\r\n");
      out.write("                                <a href=\"notmade.html\" target=\"iframe1\">\r\n");
      out.write("                                    <span>遍历二叉树</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                         </li>\r\n");
      out.write("                         <li>\r\n");
      out.write("                                <a href=\"notmade.html\" target=\"iframe1\">\r\n");
      out.write("                                    <span>哈夫曼树编码</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                          </li>\r\n");
      out.write("                          <li>\r\n");
      out.write("                                <a href=\"notmade.html\" target=\"iframe1\">\r\n");
      out.write("                                    <span>哈夫曼译码</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                          </li>\r\n");
      out.write("                          </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("                    <li class=\"main-menu-li\"><span>栈和队列</span>\r\n");
      out.write("                    \t<ul class=\"child-menu-ul\">\r\n");
      out.write("                    \t<li>\r\n");
      out.write("                                <a href=\"notmade.html\" target=\"iframe1\">\r\n");
      out.write("                                    <span>入栈</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                          </li>\r\n");
      out.write("                          <li>\r\n");
      out.write("                                <a href=\"notmade.html\" target=\"iframe1\">\r\n");
      out.write("                                    <span>出栈</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                          </li>\r\n");
      out.write("                          <li>\r\n");
      out.write("                                <a href=\"notmade.html\" target=\"iframe1\">\r\n");
      out.write("                                    <span>入队</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                          </li>\r\n");
      out.write("                          <li>\r\n");
      out.write("                                <a href=\"notmade.html\" target=\"iframe1\">\r\n");
      out.write("                                    <span>出队</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                          </li>\r\n");
      out.write("                          </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("                    <li class=\"main-menu-li\"><span>线性表和链表</span>\r\n");
      out.write("                    \t<ul class=\"child-menu-ul\">\r\n");
      out.write("                   \t \t<li>\r\n");
      out.write("                                <a href=\"notmade.html\" target=\"iframe1\">\r\n");
      out.write("                                    <span>线性表</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                         </li>\r\n");
      out.write("                         <li>\r\n");
      out.write("                                <a href=\"notmade.html\" target=\"iframe1\">\r\n");
      out.write("                                    <span>单链表</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                         </li>\r\n");
      out.write("                         <li>\r\n");
      out.write("                                <a href=\"notmade.html\" target=\"iframe1\">\r\n");
      out.write("                                    <span>循环链表</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                          </li>\r\n");
      out.write("                          </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"content\">\r\n");
      out.write("    <iframe id=\"dynamic_container\" name=\"iframe1\" src=\"hello.html\"></iframe>\r\n");
      out.write("</div>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/global.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /main/index.jsp(22,13) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${search_result}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /main/index.jsp(22,13) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("alist");
      // /main/index.jsp(22,13) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("status");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("           \t\t\t<p><a href=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${alist.algourl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"  target=\"iframe1\" onclick=\"t_hidden()\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${alist.algoname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></p>\r\n");
            out.write("           \t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
